BEGIN;

INSERT INTO 'field' VALUES('ash','ASHRAE thermal sensation',NULL);
INSERT INTO 'field' VALUES('tsa',NULL,NULL);
INSERT INTO 'field' VALUES('mci',NULL,NULL);
INSERT INTO 'field' VALUES('vent',NULL,NULL);
INSERT INTO 'field' VALUES('avm',NULL,NULL);
INSERT INTO 'field' VALUES('comf',NULL,NULL);
INSERT INTO 'field' VALUES('act10',NULL,NULL);
INSERT INTO 'field' VALUES('act20',NULL,NULL);
INSERT INTO 'field' VALUES('act30',NULL,NULL);
INSERT INTO 'field' VALUES('act60',NULL,NULL);
INSERT INTO 'field' VALUES('met','Metabolic rate','MET');
INSERT INTO 'field' VALUES('clo','Clothing level','CLO');
INSERT INTO 'field' VALUES('upholst',NULL,NULL);
INSERT INTO 'field' VALUES('insul',NULL,NULL);
INSERT INTO 'field' VALUES('ta_h','Drybulb temperature high','C');
INSERT INTO 'field' VALUES('ta_m','Drybulb temperature mid','C');
INSERT INTO 'field' VALUES('ta_l','Drybulb temperature low','C');
INSERT INTO 'field' VALUES('dewpt','Dewpoint temperature','C');
INSERT INTO 'field' VALUES('prta_b',NULL,'C');
INSERT INTO 'field' VALUES('tg_h','Globe temperature high','C');
INSERT INTO 'field' VALUES('tg_m','Globe temperature mid','C');
INSERT INTO 'field' VALUES('tg_l','Globe temperature low','C');
INSERT INTO 'field' VALUES('vel_h','Air speed high','m/s');
INSERT INTO 'field' VALUES('vel_m','Air speed mid','m/s');
INSERT INTO 'field' VALUES('vel_l','Air speed low','m/s');
INSERT INTO 'field' VALUES('turb_h','Turbulence high','%');
INSERT INTO 'field' VALUES('turb_m','Turbulence mid','%');
INSERT INTO 'field' VALUES('turb_l','Turbulence low','%');
INSERT INTO 'field' VALUES('taav',NULL,'C');
INSERT INTO 'field' VALUES('trav',NULL,'C');
INSERT INTO 'field' VALUES('top','Operative temperature','C');
INSERT INTO 'field' VALUES('velav','Average air speed','m/s');
INSERT INTO 'field' VALUES('velmax','Maximum air speed','m/s');
INSERT INTO 'field' VALUES('tuav',NULL,'%');
INSERT INTO 'field' VALUES('rh','Relative humidity','%');

INSERT INTO 'building' VALUES(1,1,'HVAC','Honolulu',NULL);
INSERT INTO 'building' VALUES(2,1,'HVAC','Honolulu',NULL);
INSERT INTO 'building' VALUES(3,1,'HVAC','Darwin',NULL);
INSERT INTO 'building' VALUES(4,1,'HVAC','Darwin',NULL);
INSERT INTO 'building' VALUES(5,1,'HVAC','Darwin',NULL);
INSERT INTO 'building' VALUES(6,1,'HVAC','Darwin',NULL);
INSERT INTO 'building' VALUES(7,1,'HVAC','Darwin',NULL);
INSERT INTO 'building' VALUES(8,1,'HVAC','Darwin',NULL);
INSERT INTO 'building' VALUES(9,1,'HVAC','Darwin',NULL);
INSERT INTO 'building' VALUES(10,1,'HVAC','Darwin',NULL);
INSERT INTO 'building' VALUES(11,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(12,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(13,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(14,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(15,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(16,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(17,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(18,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(19,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(20,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(21,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(22,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(23,1,'HVAC','Honolulu',NULL);
INSERT INTO 'building' VALUES(24,1,'HVAC','Honolulu',NULL);
INSERT INTO 'building' VALUES(25,1,'HVAC','Bangkok',NULL);
INSERT INTO 'building' VALUES(26,1,'HVAC','Bangkok',NULL);
INSERT INTO 'building' VALUES(27,1,'HVAC','Brisbane',NULL);
INSERT INTO 'building' VALUES(28,1,'HVAC','Brisbane',NULL);
INSERT INTO 'building' VALUES(29,1,'HVAC','Brisbane',NULL);
INSERT INTO 'building' VALUES(30,1,'HVAC','Brisbane',NULL);
INSERT INTO 'building' VALUES(31,1,'HVAC','Brisbane',NULL);
INSERT INTO 'building' VALUES(32,1,'HVAC','Jakarta',NULL);
INSERT INTO 'building' VALUES(33,1,'HVAC','Jakarta',NULL);
INSERT INTO 'building' VALUES(34,1,'HVAC','Jakarta',NULL);
INSERT INTO 'building' VALUES(35,1,'HVAC','Jakarta',NULL);
INSERT INTO 'building' VALUES(36,1,'HVAC','Jakarta',NULL);
INSERT INTO 'building' VALUES(37,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(38,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(39,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(40,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(41,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(42,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(43,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(44,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(45,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(46,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(47,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(48,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(49,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(50,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(51,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(52,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(53,1,'HVAC','Melbourne',NULL);
INSERT INTO 'building' VALUES(54,1,'HVAC','Melbourne',NULL);
INSERT INTO 'building' VALUES(55,1,'HVAC','Melbourne',NULL);
INSERT INTO 'building' VALUES(56,1,'HVAC','Melbourne',NULL);
INSERT INTO 'building' VALUES(57,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(58,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(59,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(60,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(61,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(62,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(63,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(64,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(65,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(66,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(67,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(68,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(69,1,'HVAC','San Francisco',NULL);
INSERT INTO 'building' VALUES(70,1,'HVAC','San Francisco',NULL);
INSERT INTO 'building' VALUES(71,1,'HVAC','San Francisco',NULL);
INSERT INTO 'building' VALUES(72,1,'HVAC','San Francisco',NULL);
INSERT INTO 'building' VALUES(73,1,'HVAC','San Francisco',NULL);
INSERT INTO 'building' VALUES(74,1,'HVAC','San Francisco',NULL);
INSERT INTO 'building' VALUES(75,1,'HVAC','San Francisco',NULL);
INSERT INTO 'building' VALUES(76,1,'HVAC','San Ramon',NULL);
INSERT INTO 'building' VALUES(77,1,'HVAC','Singapore',NULL);
INSERT INTO 'building' VALUES(78,1,'HVAC','South Wales',NULL);
INSERT INTO 'building' VALUES(79,1,'HVAC','South Wales',NULL);
INSERT INTO 'building' VALUES(80,1,'HVAC','South Wales',NULL);
INSERT INTO 'building' VALUES(81,1,'HVAC','South Wales',NULL);
INSERT INTO 'building' VALUES(82,1,'HVAC','Darwin',NULL);
INSERT INTO 'building' VALUES(83,1,'HVAC','Darwin',NULL);
INSERT INTO 'building' VALUES(84,1,'HVAC','Darwin',NULL);
INSERT INTO 'building' VALUES(85,1,'HVAC','Darwin',NULL);
INSERT INTO 'building' VALUES(86,1,'HVAC','Darwin',NULL);
INSERT INTO 'building' VALUES(87,1,'HVAC','Darwin',NULL);
INSERT INTO 'building' VALUES(88,1,'HVAC','Darwin',NULL);
INSERT INTO 'building' VALUES(89,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(90,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(91,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(92,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(93,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(94,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(95,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(96,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(97,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(98,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(99,1,'HVAC','Townsville',NULL);
INSERT INTO 'building' VALUES(100,1,'HVAC','Antioch',NULL);
INSERT INTO 'building' VALUES(101,1,'HVAC','Auburn',NULL);
INSERT INTO 'building' VALUES(102,1,'HVAC','Grand Rapids',NULL);
INSERT INTO 'building' VALUES(103,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(104,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(105,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(106,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(107,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(108,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(109,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(110,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(111,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(112,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(113,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(114,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(115,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(116,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(117,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(118,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(119,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(120,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(121,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(122,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(123,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(124,1,'HVAC','Kalgoorlie',NULL);
INSERT INTO 'building' VALUES(125,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(126,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(127,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(128,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(129,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(130,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(131,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(132,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(133,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(134,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(135,1,'HVAC','Montreal',NULL);
INSERT INTO 'building' VALUES(136,1,'HVAC','Otawa',NULL);
INSERT INTO 'building' VALUES(137,1,'HVAC','Otawa',NULL);
INSERT INTO 'building' VALUES(138,1,'HVAC','Otawa',NULL);
INSERT INTO 'building' VALUES(139,1,'HVAC','Otawa',NULL);
INSERT INTO 'building' VALUES(140,1,'HVAC','San Francisco',NULL);
INSERT INTO 'building' VALUES(141,1,'HVAC','San Francisco',NULL);
INSERT INTO 'building' VALUES(142,1,'HVAC','San Francisco',NULL);
INSERT INTO 'building' VALUES(143,1,'HVAC','San Francisco',NULL);
INSERT INTO 'building' VALUES(144,1,'HVAC','San Francisco',NULL);
INSERT INTO 'building' VALUES(145,1,'HVAC','San Francisco',NULL);
INSERT INTO 'building' VALUES(146,1,'HVAC','San Francisco',NULL);
INSERT INTO 'building' VALUES(147,1,'HVAC','San Ramon',NULL);
INSERT INTO 'building' VALUES(148,1,'HVAC','San Ramon',NULL);
INSERT INTO 'building' VALUES(149,1,'HVAC','South Wales',NULL);
INSERT INTO 'building' VALUES(150,1,'HVAC','South Wales',NULL);
INSERT INTO 'building' VALUES(151,1,'HVAC','South Wales',NULL);
INSERT INTO 'building' VALUES(152,1,'HVAC','South Wales',NULL);
INSERT INTO 'building' VALUES(153,1,'HVAC','Sydney',NULL);
INSERT INTO 'building' VALUES(154,1,'Mixed','Jakarta',NULL);
INSERT INTO 'building' VALUES(155,1,'Mixed','Sydney',NULL);
INSERT INTO 'building' VALUES(156,1,'Mixed','Merseyside',NULL);
INSERT INTO 'building' VALUES(157,1,'Mixed','Sydney',NULL);
INSERT INTO 'building' VALUES(158,1,'NV','Athens',NULL);
INSERT INTO 'building' VALUES(159,1,'NV','Athens',NULL);
INSERT INTO 'building' VALUES(160,1,'NV','Athens',NULL);
INSERT INTO 'building' VALUES(161,1,'NV','Athens',NULL);
INSERT INTO 'building' VALUES(162,1,'NV','Athens',NULL);
INSERT INTO 'building' VALUES(163,1,'NV','Athens',NULL);
INSERT INTO 'building' VALUES(164,1,'NV','Bangkok',NULL);
INSERT INTO 'building' VALUES(165,1,'NV','Bangkok',NULL);
INSERT INTO 'building' VALUES(166,1,'NV','Bangkok',NULL);
INSERT INTO 'building' VALUES(167,1,'NV','Brisbane',NULL);
INSERT INTO 'building' VALUES(168,1,'NV','Brisbane',NULL);
INSERT INTO 'building' VALUES(169,1,'NV','Brisbane',NULL);
INSERT INTO 'building' VALUES(170,1,'NV','Brisbane',NULL);
INSERT INTO 'building' VALUES(171,1,'NV','Brisbane',NULL);
INSERT INTO 'building' VALUES(172,1,'NV','Honolulu',NULL);
INSERT INTO 'building' VALUES(173,1,'NV','Honolulu',NULL);
INSERT INTO 'building' VALUES(174,1,'NV','Honolulu',NULL);
INSERT INTO 'building' VALUES(175,1,'NV','Honolulu',NULL);
INSERT INTO 'building' VALUES(176,1,'NV','Jakarta',NULL);
INSERT INTO 'building' VALUES(177,1,'NV','Karachi',NULL);
INSERT INTO 'building' VALUES(178,1,'NV','Melbourne',NULL);
INSERT INTO 'building' VALUES(179,1,'NV','Melbourne',NULL);
INSERT INTO 'building' VALUES(180,1,'NV','Melbourne',NULL);
INSERT INTO 'building' VALUES(181,1,'NV','Merseyside',NULL);
INSERT INTO 'building' VALUES(182,1,'NV','Merseyside',NULL);
INSERT INTO 'building' VALUES(183,1,'NV','Merseyside',NULL);
INSERT INTO 'building' VALUES(184,1,'NV','Multan',NULL);
INSERT INTO 'building' VALUES(185,1,'NV','Oxford',NULL);
INSERT INTO 'building' VALUES(186,1,'NV','Oxford',NULL);
INSERT INTO 'building' VALUES(187,1,'NV','Oxford',NULL);
INSERT INTO 'building' VALUES(188,1,'NV','Peshawar',NULL);
INSERT INTO 'building' VALUES(189,1,'NV','Quettar',NULL);
INSERT INTO 'building' VALUES(190,1,'NV','Saidu',NULL);
INSERT INTO 'building' VALUES(191,1,'NV','San Francisco',NULL);
INSERT INTO 'building' VALUES(192,1,'NV','San Francisco',NULL);
INSERT INTO 'building' VALUES(193,1,'NV','San Francisco',NULL);
INSERT INTO 'building' VALUES(194,1,'NV','Singapore',NULL);
INSERT INTO 'building' VALUES(195,1,'NV','Honolulu',NULL);
INSERT INTO 'building' VALUES(196,1,'NV','Honolulu',NULL);
INSERT INTO 'building' VALUES(197,1,'NV','Honolulu',NULL);
INSERT INTO 'building' VALUES(198,1,'NV','Honolulu',NULL);
INSERT INTO 'building' VALUES(199,1,'NV','Karachi',NULL);
INSERT INTO 'building' VALUES(200,1,'NV','Merseyside',NULL);
INSERT INTO 'building' VALUES(201,1,'NV','Merseyside',NULL);
INSERT INTO 'building' VALUES(202,1,'NV','Merseyside',NULL);
INSERT INTO 'building' VALUES(203,1,'NV','Merseyside',NULL);
INSERT INTO 'building' VALUES(204,1,'NV','Merseyside',NULL);
INSERT INTO 'building' VALUES(205,1,'NV','Peshawar',NULL);
INSERT INTO 'building' VALUES(206,1,'NV','Quettar',NULL);
INSERT INTO 'building' VALUES(207,1,'NV','Saidu',NULL);
INSERT INTO 'building' VALUES(208,1,'NV','San Francisco',NULL);
INSERT INTO 'building' VALUES(209,1,'NV','San Francisco',NULL);
INSERT INTO 'building' VALUES(210,1,'NV','San Francisco',NULL);

COMMIT;
